### ISSUE TITLE
Cant setup networking on hummingbird

### ISSUE THREAD

**Issue by Akorn27** [Sweets/hummingbird#22]

**Comment by Sweets** [comment]
Please be more descriptive when opening issues. The only provided information is that you can't get networking to work, which does not help me help you.

Provide some context, such as providing your `interlude` stage file contents, what you're using to try to setup networking, whether you're calling dhcpcd or you're using a static address.

Opening issues with no provided information does nothing, and it doesn't particularly entice me to want to respond either when I could likely just say it's going to be user error. I don't mind helping, but I need something to work with.

**Comment by Akorn27** [comment]
Forgot myself abit, stock file w/dhcp calls, and ifconfig

**Comment by Sweets** [comment]
`interlude` has no stock file. It's only entirely user defined because not everyone will have a need for that specific stage. Just show me the contents of your interlude file.

Also, `ifconfig` has long since been deprecated in the land of Linux. Use `ip`. Anyways, just saying "dhcp calls and ifconfig" still does not help me. The reason I am asking for the file contents in particular is because it could easily be a typo, or a misuse of commands, something that I can't actually tell you without seeing it myself.

While we're at it, check the file's MIME. Make sure it isn't another case of #21.

**Comment by Akorn27** [comment]
![image](https://user-images.githubusercontent.com/61843348/126138086-dde24843-62e5-4a00-8414-16fdd2aa490a.png)
And, no, interlude works this time.

**Comment by Sweets** [comment]
If you chroot into your partition that contains busybox and run the exact same commands as in your interlude stage, what is the result? I don't imagine that this is going to be a problem created by hummingbird, and that your series of commands with `ifconfig` and `udhcpc` aren't going to work even outside of hummingbird.
